import { Tender } from './types';

export const mockTenders: Tender[] = [
  {
    id: '1',
    title: 'Construction of 4-Lane Highway NH-44 (Km 120 to Km 185)',
    organization: 'National Highways Authority of India',
    state: 'Uttar Pradesh',
    category: 'construction',
    value: 45000000,
    deadline: '2026-06-15',
    publishedDate: '2026-05-10',
    status: 'active',
    tenderNo: 'NHAI/UP/2026/0451',
    description: 'Construction and maintenance of 4-lane highway including flyovers, underpasses and service roads.',
    documents: ['NIT.pdf', 'BOQ.xlsx', 'Drawings.zip'],
    emd: 900000,
    bidFee: 5000,
    isPremium: false,
  },
  {
    id: '2',
    title: 'Supply of Medical Equipment to District Hospitals',
    organization: 'Rajasthan Medical Services Corporation',
    state: 'Rajasthan',
    category: 'healthcare',
    value: 8500000,
    deadline: '2026-06-02',
    publishedDate: '2026-05-12',
    status: 'active',
    tenderNo: 'RMSC/JY/2026/0892',
    description: 'Procurement of ventilators, ICU beds, and diagnostic equipment for 50 district hospitals.',
    documents: ['Tender_Doc.pdf', 'Tech_Specs.pdf'],
    emd: 170000,
    bidFee: 2000,
    isPremium: false,
  },
  {
    id: '3',
    title: 'IT Infrastructure Upgrade — Data Center Modernization',
    organization: 'National Informatics Centre',
    state: 'Delhi',
    category: 'it',
    value: 22000000,
    deadline: '2026-05-28',
    publishedDate: '2026-05-05',
    status: 'active',
    tenderNo: 'NIC/DL/2026/IT/0234',
    description: 'Upgrade of servers, storage systems, networking equipment for National Data Center.',
    documents: ['RFP.pdf', 'SLA_Requirements.pdf'],
    emd: 440000,
    bidFee: 10000,
    isPremium: true,
  },
  {
    id: '4',
    title: 'Construction of 500 Smart Classrooms in Government Schools',
    organization: 'Samagra Shiksha Abhiyan Maharashtra',
    state: 'Maharashtra',
    category: 'education',
    value: 12500000,
    deadline: '2026-06-20',
    publishedDate: '2026-05-14',
    status: 'active',
    tenderNo: 'SSA/MH/2026/0567',
    description: 'Installation of interactive panels, projectors, and digital learning infrastructure.',
    documents: ['NIT.pdf', 'BOQ.pdf', 'Technical_Specs.pdf'],
    emd: 250000,
    bidFee: 3000,
    isPremium: false,
  },
  {
    id: '5',
    title: 'Solar Power Plant 50MW Grid Connected',
    organization: 'Gujarat Energy Development Agency',
    state: 'Gujarat',
    category: 'infrastructure',
    value: 180000000,
    deadline: '2026-07-01',
    publishedDate: '2026-05-01',
    status: 'active',
    tenderNo: 'GEDA/GJ/2026/SOL/0089',
    description: 'Development of 50MW solar power plant with grid connectivity and transmission infrastructure.',
    documents: ['RFP.pdf', 'Land_Details.pdf', 'Grid_Code.pdf'],
    emd: 3600000,
    bidFee: 25000,
    isPremium: true,
  },
  {
    id: '6',
    title: 'Army Canteen Supply Rations and Provisions Annual Contract',
    organization: 'Ministry of Defence',
    state: 'Haryana',
    category: 'defense',
    value: 5600000,
    deadline: '2026-05-25',
    publishedDate: '2026-05-08',
    status: 'active',
    tenderNo: 'MOD/HR/2026/CSD/0341',
    description: 'Annual supply contract for rations, dry provisions and consumables for Army canteens.',
    documents: ['Tender_Notice.pdf', 'Item_List.xlsx'],
    emd: 112000,
    bidFee: 1000,
    isPremium: false,
  },
];

export const states = ['All States', 'Delhi', 'Maharashtra', 'Uttar Pradesh', 'Gujarat', 'Rajasthan', 'Haryana', 'Karnataka', 'Tamil Nadu'];
export const categories = ['All Categories', 'construction', 'it', 'healthcare', 'education', 'defense', 'infrastructure'];
